linters-settings:
  lll:
    line-length: 140
  depguard:
    rules:
      main:
        files:
          - "$all"
          - "!$test"
        allow:
          - "$gostd"
          - github.com/
      tests:
        files:
          - "$test"
        allow:
          - "$gostd"
          - github.com/

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused

  # don't enable:
  # - whitespace
  # - asciicheck
  # - gochecknoglobals
  # - gocognit
  # - godot
  # - godox
  # - goerr113
  # - maligned
  # - nestif
  # - prealloc
  # - testpackage
  # - wsl
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - exportloopref
        - lll
    # enforce ALL_CAPS constant naming for tags
    - linters:
        - revive
      path: rscp/tag.go
      text: "var-naming: don't use ALL_CAPS in Go names; use CamelCase"
    # enforce ALL_CAPS constant naming for tags
    - linters:
        - stylecheck
      path: rscp/tag.go
      text: "ST1003: should not use ALL_CAPS in Go names; use CamelCase instead"
